env:
  numEnvs: 1
  numAgents: 1
  envSpacing: 5.0
  enableDebugVis: False
  isFlagrun: False
  maxEpisodeLength: 30000 
  pdControl: True
  powerScale: 1.0
  controlFrequencyInv: 4
  controlFrequencyLow: 8
  imgDelayFrame: 4

  liftedSuccessThreshold: 0.3
  liftedInitThreshold: 0.05
  baseObjectDisThreshold: 0.6
  holdSteps: 25
  lastCommands: False

  low_policy_path: "data/low_policy/model_37000.pt"

  asset:
    assetRoot: "data/asset"
    assetFileRobot: "b1z1-col/urdf/b1z1.urdf"
    assetFileObj: "obj_set/"

    asset_multi:
      blue_tea_box:
        dict_idx: 12
        height: 0.037
        orientation: [0.0, 0.0, 0.0, 1.0]
        scale: 1.0
    control:
        stiffness: {'joint': 80, 'z1': 5}  # [N*m/rad]
        damping: {'joint': 2.0, 'z1': 0.5}     # [N*m*s/rad]

  plane:
    staticFriction: 1.0
    dynamicFriction: 1.0
    restitution: 0.0
  
physics_engine: "physx"

sim:
  substeps: 1
  use_gpu_pipeline: True
  up_axis: "z"
  gravity: [0.0, 0.0, -9.81]
  dt: 0.005

  physx:
    use_gpu: True
    num_threads: 4
    solver_type: 1
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 50.0
    default_buffer_size_multiplier: 100.0
    max_gpu_contact_pairs: 1000000 #284032

reward:
  base_height_target: 0.55
  only_positive_rewards: False
  scales:
    approaching: 0.5
    lifting: 1.0
    pick_up: 3.5 # 0.5
    acc_penalty: -0.001
    command_penalty: -1.0
    command_reward: 0.25
    standpick: 0.25
    action_rate: -0.001
    ee_orn: 0.01
    base_dir: 0.25
    rad_penalty: 0.0
    base_ang_pen: 0.0
    base_approaching: 0.01 # 0.05
    grasp_base_height: 0.5
    gripper_rate: 0.0 # -0.1
        
sensor:
  depth_clip_lower: 0.15
  depth_clip_rand_range: [0.18, 0.25]
  enableCamera: False # True
  resized_resolution: [96, 54]
  onboard_camera:
    horizontal_fov: 69
    resolution: [96, 54] 
    position: [0.425, 0.04, 0.12]
    rotation: [0.0, 0.0, 0.0]
  wrist_camera:
    horizontal_fov: 69
    resolution: [96, 54]
    # position: [0.0951, 0.191, -0.03175] # Estimate
    position: [0.0955, 0.22, -0.03175] # Fix the real offset height
    # position: [0.1091, 0.191, -0.03175] # Fix the real offset
    # position: [0.0623, 0.191, -0.03175]
    rotation: [-1.57, 0.0, -0.87] #-0.52, -0.347 -0.87
    rand_position: [0.005, 0.005, 0.005]